# Generated by Django 3.2.12 on 2022-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=255)),
                ('password', models.CharField(db_column='PassWord', max_length=255)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodid', models.AutoField(db_column='foodID', primary_key=True, serialize=False)),
                ('foodname', models.CharField(blank=True, max_length=255, null=True)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('expireddate', models.DateField(blank=True, db_column='expiredDate', null=True)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='Order_ID', primary_key=True, serialize=False)),
                ('order_type', models.IntegerField(blank=True, db_column='Order_Type', null=True)),
                ('order_quantity', models.IntegerField(blank=True, db_column='Order_quantity', null=True)),
                ('order_amount', models.DecimalField(blank=True, db_column='Order_Amount', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('tel_number', models.IntegerField(blank=True, db_column='Tel_Number', null=True)),
                ('password', models.IntegerField(blank=True, db_column='PassWord', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=32, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=32, null=True)),
                ('balance', models.DecimalField(blank=True, db_column='Balance', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
