# Generated by Django 3.2.5 on 2022-05-10 09:43

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payments', '0002_admin_food_interests_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, default='', max_length=256, verbose_name='nickname')),
                ('tel_number', models.CharField(blank=True, default='', max_length=256, verbose_name='tel_number')),
                ('gender', models.CharField(blank=True, default='', max_length=255, verbose_name='gender')),
                ('type', models.CharField(blank=True, default='', max_length=255, verbose_name='type')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='balance')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='last_name')),
                ('status', models.IntegerField(blank=True, default=0, verbose_name='status')),
                ('version', models.IntegerField(blank=True, default=0, verbose_name='version')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='modify_time')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'profile',
                'db_table': 'profile',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseDate', models.DateField(max_length=32, verbose_name='releaseDate')),
                ('expiredDate', models.DateField(max_length=32, verbose_name='expiredDate')),
                ('categories', models.CharField(max_length=15, verbose_name='categories')),
                ('price', models.EmailField(max_length=32, verbose_name='price')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('quantity', models.EmailField(max_length=32, verbose_name='quantity')),
                ('postcode', models.CharField(max_length=32, verbose_name='postcode')),
                ('location', models.CharField(max_length=32, verbose_name='location')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
