# Generated by Django 3.2.10 on 2022-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='index',
            new_name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='金额'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel_number',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='类别'),
        ),
    ]
